name: Python run

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     token: ${{secrets.ACCESS_TOKEN}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run python
      run: python createCSV.py
    - name: CSV commit
      run: |
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.NAME}}
          git add .
          git commit -m "add CSV"
          git push origin main
         
